### ISSUE TITLE
用了这一段代码访问localhost:3000没有输出Hello world啊

### ISSUE THREAD

**Issue by 0xlc** [cevio/koa-rapid-router#4]
const Koa = require('koa');
const Router = require('koa-rapid-router')
// 创建服务对象容器
const app = new Koa();
const routerContianer = new Router();
// 生成路由对象
const router = routerContianer.create(/*prefix: default '/'*/);
// 注入中间件
router.use(async (ctx, next) => {
  console.log(ctx.path);
  await next();
});
// 注入路由
router.get('/', async ctx => ctx.body = 'Hello world!');
// 链接中间件到KOA
app.use(routerContianer.Koa());
// 启动服务
app.listen(3000, err => {
  if (err) throw err;
  console.log('Server run at 3000');
});

**Comment by five-dev-7** [comment]
你是不是在window下使用的？
如果是，访问这个地址：https://gitee.com/five77/breeze-web-router
或者使用 npm install breeze-web-router 。用法和rapid-router的一样，我测试后再提PR

**Comment by five-dev-7** [comment]
> const Koa = require('koa');
> const Router = require('koa-rapid-router')
> // 创建服务对象容器
> const app = new Koa();
> const routerContianer = new Router();
> // 生成路由对象
> const router = routerContianer.create(/_prefix: default '/'_/);
> // 注入中间件
> router.use(async (ctx, next) => {
> console.log(ctx.path);
> await next();
> });
> // 注入路由
> router.get('/', async ctx => ctx.body = 'Hello world!');
> // 链接中间件到KOA
> app.use(routerContianer.Koa());
> // 启动服务
> app.listen(3000, err => {
> if (err) throw err;
> console.log('Server run at 3000');
> });

你是不是在window下使用的？
如果是，访问这个地址：https://gitee.com/five77/breeze-web-router
或者使用 npm install breeze-web-router 。用法和rapid-router的一样，我测试后再提PR
